Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/LineLength:
  Max: 120  

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 30

AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/**/*'
    - !ruby/regexp /old_and_unused\.rb$/  
