---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/couriers":
    post:
      summary: couriers/
      tags:
      - Couriers
      description: Endpoint for creating couriers data
      parameters: []
      responses:
        '201':
          description: courier created
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
              required:
              - name
              - email
    get:
      summary: couriers/
      tags:
      - Couriers
      description: Endpoint for showing all couriers data
      parameters: []
      responses:
        '201':
          description: index couriers
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
              required:
              - name
              - email
  "/couriers/new":
    get:
      summary: couriers/new
      tags:
      - Couriers
      description: Endpoint for creating courier
      parameters: []
      responses:
        '201':
          description: new couriers
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
              required:
              - name
              - email
  "/couriers/{id}":
    get:
      summary: couriers/:courier_id
      tags:
      - Couriers
      description: Endpoint for showing couriers data
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: courier found
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  email:
                    type: string
                required:
                - id
                - name
                - email
            application/xml:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  email:
                    type: string
                required:
                - id
                - name
                - email
        '404':
          description: courier not found
    put:
      summary: couriers/:courier_id
      tags:
      - Couriers
      description: Endpoint for updating couriers data
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: courier found
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  email:
                    type: string
                required:
                - id
                - name
                - email
            application/xml:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  email:
                    type: string
                required:
                - id
                - name
                - email
        '404':
          description: courier not found
    delete:
      summary: couriers/:courier_id
      tags:
      - Couriers
      description: Endpoint for delete courier
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: courier found
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  email:
                    type: string
                required:
                - id
                - name
                - email
            application/xml:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  email:
                    type: string
                required:
                - id
                - name
                - email
        '404':
          description: courier not found
  "/couriers/{id}/packages":
    post:
      summary: couriers/:courier_id/packages/
      tags:
      - Packages
      description: Endpoint for creating packages data
      parameters: []
      responses:
        '201':
          description: package created
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                delivery_status:
                  type: string
                estimated_delivery_date:
                  type: date
                tracking_number:
                  type: string
                courier_id:
                  type: string
              required:
              - delivery status
              - estimated delivery_date
              - tracking number
  "/package_assignments":
    post:
      summary: package_assignments/
      tags:
      - PackageAssignments
      description: Endpoint for creating package assignment
      parameters: []
      responses:
        '201':
          description: package assignment created
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                package_id:
                  type: string
                courier_id:
                  type: string
              required:
              - package_id
              - courier_id
    get:
      summary: package_assignments/
      tags:
      - PackageAssignments
      security:
      - basic_auth: []
      description: Endpoint for showing all package_assignments data
      parameters: []
      responses:
        '201':
          description: package_assignments
        '401':
          description: authentication failed
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                package_id:
                  type: string
                courier_id:
                  type: string
              required:
              - package_id
              - courier_id
  "/package_assignments/new":
    get:
      summary: package_assignments/new/
      tags:
      - PackageAssignments
      description: Endpoint for creating new package_assignment
      parameters: []
      responses:
        '201':
          description: new package_assignments
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                package_id:
                  type: string
                courier_id:
                  type: string
              required:
              - package_id
              - courier_id
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
components:
  securitySchemes:
    basic_auth:
      type: http
      scheme: basic
    api_key:
      type: apiKey
      name: api_key
      in: query
